/**
 * The preset profile avatars users can pick from.
 * The artwork itself is generated by scripts/generate-avatars.mjs into
 * /public/avatars — keep the ids below in sync with that script.
 */

export interface AvatarPreset {
  id: string;
  label: string;
  url: string;
}

const IDS: Array<[id: string, label: string]> = [
  ['invader', 'Invader'],
  ['skull', 'Skull'],
  ['ghost', 'Ghost'],
  ['heart', 'Pixel Heart'],
  ['cartridge', 'Cartridge'],
  ['dpad', 'D-Pad'],
  ['robot', 'Robot'],
  ['alien', 'Alien'],
  ['sword', 'Sword'],
  ['potion', 'Potion'],
  ['coin', 'Coin'],
  ['visor', 'Visor'],
];

export const AVATAR_PRESETS: AvatarPreset[] = IDS.map(([id, label]) => ({
  id,
  label,
  url: `/avatars/${id}.svg`,
}));

/** Is this one of the preset avatars? Mirrors the DB constraint in migration 010. */
export function isPresetAvatar(url: string | null): boolean {
  return !!url && AVATAR_PRESETS.some((preset) => preset.url === url);
}
